/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "sensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MftmConfig, MftmConfig, AUTO)


PB_BIND(Kx134Config, Kx134Config, AUTO)


PB_BIND(ads124s08Config, ads124s08Config, AUTO)


PB_BIND(saadcConfig, saadcConfig, AUTO)


PB_BIND(micConfig, micConfig, AUTO)


PB_BIND(Acceleration, Acceleration, AUTO)


PB_BIND(Microphone, Microphone, AUTO)


PB_BIND(Temperature, Temperature, AUTO)


PB_BIND(Force, Force, AUTO)


PB_BIND(OdrFreqData, OdrFreqData, AUTO)


PB_BIND(Battery, Battery, AUTO)


PB_BIND(HostPC, HostPC, AUTO)


PB_BIND(SrimStatus, SrimStatus, AUTO)


PB_BIND(MftmStatus, MftmStatus, AUTO)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

